### ISSUE TITLE
Menu item ordering testing error

### ISSUE THREAD

**Issue by janno42** [fsr-de/1327#638]
`test_menu_item_ordering` often locally fails for unknown reasons. this can happen even if nothing about menu items has changed in the testing instance.
```
FAIL: test_menu_item_ordering (_1327.main.tests.MenuItemTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/_1327/main/tests.py", line 357, in test_menu_item_ordering
    self.assertEqual(menu_item.id, int(menu_item_id), 'Menu Item ordering is not as expected')
AssertionError: 10 != 9 : Menu Item ordering is not as expected
```

**Comment by Bartzi** [comment]
This seems to fail only for vagrant users. I suspect this is a problem with Postgres... Would be intersting to see if this fails on production, too...

**Comment by cmfcmf** [comment]
I'm using Python natively on Windows 10: It works fine when installing `psycopg2 == 2.6.2` (the same version as installed on the server) and fails when installing `psycopg2 == 2.7.6.1`.

**Comment by cmfcmf** [comment]
I think this happens because the test orders the menu items strictly by "order", discarding the parent-child relationship.
https://github.com/fsr-de/1327/blob/07f3bb925e2ceca46fc86e839d64aea461e1b0f4/_1327/main/tests.py#L344

Compare this to the code used in the view:

https://github.com/fsr-de/1327/blob/07f3bb925e2ceca46fc86e839d64aea461e1b0f4/_1327/main/views.py#L60-L81

Take this example (itemnames and order):

```
root 5
-- child1 7
---- child2 4
---- child3 5
-- child4 8
```

Correct order: `root, child1, child2, child3, child4`.
Ordering by order: `root, child2, child3, child1, child4`

I think the randomness happens due to the fact that Mommy assigns random order numbers when creating the menu items: https://github.com/fsr-de/1327/blob/07f3bb925e2ceca46fc86e839d64aea461e1b0f4/_1327/main/tests.py#L79-L81
